version: 0.2.1-{branch}-{build}

environment:
    global:
        RUST_BACKTRACE: full
        RUST_TEST_THREADS: 1
    matrix:
        - channel: nightly
          target: x86_64-pc-windows-msvc
          filename: dowser-x64.exe

install:
    - curl -sSf -o rustup-init.exe https://win.rustup.rs/
    - rustup-init.exe -y --default-host %target% --default-toolchain %channel%
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - rustc -vV
    - cargo -vV
    - rustup component add rustfmt-preview

cache:
    - '%USERPROFILE%\.cargo'

build: off

build_script: cargo build

test_script:
    - cargo fmt --all -- --check
    - cargo test --verbose --all -- --nocapture

after_test:
    - cargo build --release --verbose
    - mkdir "dowser-redist-%APPVEYOR_BUILD_VERSION%"
    - move "target\release\dowser.exe" "dowser-redist-%APPVEYOR_BUILD_VERSION%\dowser.exe"
    - curl -LsSf -o ike-scan.zip https://github.com/royhills/ike-scan/releases/download/1.9/ike-scan-win32-1.9.zip
    - unzip ike-scan.zip
    - move ike-scan.exe "dowser-redist-%APPVEYOR_BUILD_VERSION%\ike-scan.exe"
    - move cygwin1.dll "dowser-redist-%APPVEYOR_BUILD_VERSION%\cygwin1.dll"

artifacts:
    - path: "dowser-redist-$(APPVEYOR_BUILD_VERSION)"

deploy:
    description: ''
    auth_token:
        secure: 5l5fHV5J1h7LjAFbbBN03PUA5mhoYkPKhHli4tuiZCSFh9Y4CUwq3Vtl9CynLby3
    provider: GitHub
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
